server:
  port: 8080
  #context-path:


management:
  security:
    enabled: false


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.27.93.16:3306/eternal
    username: eternal
    password: eternal





myConfig:
  name: eternal